### ISSUE TITLE
New Datatype to support CableInfo

### ISSUE THREAD

**Issue by EmilieSkog** [Sveino/AssetCatalog#2]
When/What do we need the pullForce attribute for?
Info: 
Name: pullForce
DataType: Force 
Description: Maximum applied pulling force.

When/What do we need the bendRadius attribute for?
Info:
Name: bendRadius
DataType: Length
Description: Minimum bending radius

**Comment by Sveino** [comment]
Two issue are created from this:
[<add link to Redmind>](https://redmine.ucaiug.org/issues/6615?issue_count=88&issue_position=1&next_issue_id=6610)
 Add new Datatype for CableInfo
The following new Datatype should be added to Grid/Base/Domain/GeneralDatatypes

Class name: <CIMDatatype>MassPerLength
Note: (old) Mass per length. Enables specification of weight without details of the cross-section.
Note (New): Mass per length. It shall be a positive value or zero.
unit:InitalValue: kgPerm

Justification:
MassPerLength is used in specifying the weight of a cable independents of the length. This is needed for catalogue data for cable and wires. 
 
Class name: <CIMDatatype>Force
Note: Force in newtons (kg·m/s²). It shall be a positive value or zero.
unit:InitalValue: N

Justification:
Force is used in specifying the maximum pull force that a cable can withstand. 

![image](https://github.com/Sveino/AssetCatalog/assets/15873106/a427989c-2be9-4733-8c86-d37d715a4c42)

**Comment by Sveino** [comment]
This got approved:
![image](https://github.com/Sveino/AssetCatalog/assets/15873106/c7803a1e-48d1-49e7-9b2b-44353ef25e02)
